stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
    outs:
      - model

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - model
    outs:
      - results